"""The minimum persistence API needed to exercise the isolation boundary.

Two repositories and nothing else. No HTTP, no accounts, no memberships, no jobs -- those
are Milestone 3 and later, and building them here would be the opportunistic
later-milestone work the working contract forbids.

The split between them *is* the privilege split:

* :class:`TenantRepository` runs on the provisioning connection, inside a provisioning
  context. It does not take a tenant id and cannot be given one: the id was generated by
  ``firmbatch.begin_tenant_provisioning()`` before this repository was reached, so the
  privileged path can create a tenant and cannot select one.
* :class:`WorkspaceRepository` runs on the restricted application connection inside an
  authenticated transaction. It writes no ``WHERE tenant_id = ...`` anywhere, on purpose:
  every query below is scoped by PostgreSQL, and a reader can check that claim by
  noticing there is no filter to get wrong.

**Neither takes a tenant id.** At Milestone 2.1 both did, so that a caller could *try* to
write across tenants and be refused. That parameter is exactly the independently supplied
identifier Milestone 2.3 removes: an argument that can disagree with the authenticated
context is an argument somebody will one day pass the wrong value to, and the refusal it
produced was a Python check standing in front of a database check that no longer needs
one. The tenant is whatever the transaction authenticated as, and there is nothing to
disagree with it.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.orm import Session

from .auth import require_authenticated_context
from .engine import current_tenant_context
from .models import Tenant, Workspace


class TenantContextMismatch(RuntimeError):
    """Raised when a caller asks for a write and the transaction has no authenticated tenant."""


@dataclass(frozen=True)
class TenantRepository:
    """Privileged tenant provisioning. Runs on the provisioning role, not the app role."""

    session: Session

    def create(self, *, slug: str, name: str) -> Tenant:
        """Create the tenant this transaction is provisioning.

        The id is **not** an argument and is not generated here. It comes from the
        provisioning context ``firmbatch.begin_tenant_provisioning()`` established, which
        generated it inside the database. That is what keeps the privileged path from
        being able to act on an existing tenant: it cannot name one.

        The isolation policy on ``tenants`` is ``id = firmbatch.auth_tenant_id()`` -- a
        tenant row is visible to exactly the tenant it is -- so inserting one is
        asserting the identity the context already carries. That self-reference is what
        lets provisioning stay under row-level security instead of needing an exemption.
        """
        context = require_authenticated_context(self.session)
        if context.actor_kind != "provisioning":
            raise TenantContextMismatch(
                "creating a tenant requires a provisioning context. Use provisioning_transaction(), "
                "which asks PostgreSQL for a fresh tenant id; a credential cannot create a tenant, "
                "because a credential already belongs to one."
            )
        tenant = Tenant(id=context.tenant_id, slug=slug, name=name)
        self.session.add(tenant)
        self.session.flush()
        return tenant

    def get(self, tenant_id: uuid.UUID) -> Tenant | None:
        """Fetch a tenant. Returns ``None`` for any tenant the context is not."""
        return self.session.get(Tenant, tenant_id)

    def visible(self) -> list[Tenant]:
        """Every tenant row this transaction can see -- at most one, by policy."""
        return list(self.session.scalars(select(Tenant).order_by(Tenant.created_at)))


@dataclass(frozen=True)
class WorkspaceRepository:
    """Tenant-scoped workspace access. Runs on the restricted application role."""

    session: Session

    def _tenant_id(self) -> uuid.UUID:
        tenant_id = current_tenant_context(self.session)
        if tenant_id is None:
            raise TenantContextMismatch(
                "this transaction has no authenticated context. The database would reject the write "
                "anyway; failing here says why. Present a credential with "
                "authenticated_transaction()."
            )
        return tenant_id

    def create(self, *, slug: str, name: str) -> Workspace:
        """Create a workspace in the tenant this transaction authenticated as.

        There is no ``tenant_id`` parameter. The row's tenant is the authenticated one,
        the ``WITH CHECK`` policy re-derives it from the same context, and the two cannot
        disagree because there is only one of them.
        """
        workspace = Workspace(tenant_id=self._tenant_id(), slug=slug, name=name)
        self.session.add(workspace)
        self.session.flush()
        return workspace

    def get(self, workspace_id: uuid.UUID) -> Workspace | None:
        """Fetch a workspace by id. Another tenant's id returns ``None``, not an error."""
        return self.session.get(Workspace, workspace_id)

    def get_by_slug(self, slug: str) -> Workspace | None:
        return self.session.scalars(select(Workspace).where(Workspace.slug == slug)).one_or_none()

    def list(self) -> list[Workspace]:
        """Every workspace visible to this transaction. No tenant filter: RLS is the filter."""
        return list(self.session.scalars(select(Workspace).order_by(Workspace.created_at, Workspace.slug)))
