"""Tenant and workspace spine with forced row-level security.

Revision ID: 0001_tenant_workspace_spine
Revises:
Create Date: 2026-09-02

The first v1 migration. It creates the dedicated ``firmbatch`` schema, the two
tenant-scoped tables, and the isolation machinery every later Milestone 2 table inherits:

* ``firmbatch.app_current_tenant_id()`` reads the transaction-local ``app.tenant_id``
  setting and returns NULL when it is unset. Not ``SECURITY DEFINER`` -- it needs no
  privilege of its own, and a definer-rights function in a policy predicate is a standing
  bypass waiting for a mistake. ``EXECUTE`` is revoked from PUBLIC and granted per role by
  ``db/roles.py``: relying on PostgreSQL's default of granting execute to PUBLIC would
  make the helper reachable by any future role that gains connect rights.
* Row-level security is ENABLEd *and* FORCEd on both tables. ENABLE alone exempts the
  table owner, which would mean the isolation tests pass while the owner connection
  quietly reads everything.
* Policies are written ``TO PUBLIC`` and name no role. Role names belong to an
  environment, not to a schema history; ``db/roles.py`` does the grants.

**Everything is schema-qualified**, including the ``search_path`` this migration runs
under and the Alembic version table (see ``migrate.py``). An unqualified relation name is
resolved through the session's temporary schema first, so a role holding the default
``TEMP`` privilege could shadow a Firmbatch table for the life of a pooled connection.
See ``db/base.py`` for the three measures that close that.

Deliberately hand-written rather than autogenerated: ``op.create_table`` cannot emit RLS
DDL, and ``tests/test_migrations.py`` asserts with ``compare_metadata`` that what this
file builds still matches ``db/models.py``.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID

revision: str = "0001_tenant_workspace_spine"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None

SCHEMA = "firmbatch"
SLUG_REGEX = r"^[a-z0-9]([a-z0-9-]{0,60}[a-z0-9])?$"

#: table -> the column compared against the tenant context. Mirrors
#: ``models.TENANT_SCOPED_TABLES``; the test suite asserts the two agree.
TENANT_SCOPED_TABLES = {"tenants": "id", "workspaces": "tenant_id"}

_UUID = UUID(as_uuid=True)
_TIMESTAMPTZ = TIMESTAMP(timezone=True)


def upgrade() -> None:
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")

    op.execute(
        f"""
        CREATE FUNCTION {SCHEMA}.app_current_tenant_id() RETURNS uuid
        LANGUAGE sql
        STABLE
        SET search_path = pg_catalog
        AS $$
            SELECT nullif(current_setting('app.tenant_id', true), '')::uuid
        $$
        """
    )
    # Do not inherit PostgreSQL's default of EXECUTE to PUBLIC. db/roles.py grants it to
    # the roles that actually evaluate the policies.
    op.execute(f"REVOKE ALL ON FUNCTION {SCHEMA}.app_current_tenant_id() FROM PUBLIC")

    op.create_table(
        "tenants",
        sa.Column("id", _UUID, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_at", _TIMESTAMPTZ, nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", _TIMESTAMPTZ, nullable=False, server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id", name="pk_tenants"),
        sa.UniqueConstraint("slug", name="uq_tenants_slug"),
        sa.CheckConstraint(f"slug ~ '{SLUG_REGEX}'", name="ck_tenants_slug_format"),
        sa.CheckConstraint("length(name) between 1 and 200", name="ck_tenants_name_length"),
        schema=SCHEMA,
    )

    op.create_table(
        "workspaces",
        sa.Column("id", _UUID, primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("tenant_id", _UUID, nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_at", _TIMESTAMPTZ, nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", _TIMESTAMPTZ, nullable=False, server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id", name="pk_workspaces"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            [f"{SCHEMA}.tenants.id"],
            name="fk_workspaces_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        # Tenant-local uniqueness. Never global: a global unique index on slug would let
        # one tenant discover another tenant's names through a constraint violation.
        sa.UniqueConstraint("tenant_id", "slug", name="uq_workspaces_tenant_id_slug"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_workspaces_tenant_id_name"),
        # Referential-integrity checks bypass row security, so later child tables must be
        # able to reference (id, tenant_id) rather than id alone.
        sa.UniqueConstraint("id", "tenant_id", name="uq_workspaces_id_tenant_id"),
        sa.CheckConstraint(f"slug ~ '{SLUG_REGEX}'", name="ck_workspaces_slug_format"),
        sa.CheckConstraint("length(name) between 1 and 200", name="ck_workspaces_name_length"),
        schema=SCHEMA,
    )
    op.create_index("ix_workspaces_tenant_id", "workspaces", ["tenant_id"], schema=SCHEMA)

    for table, tenant_column in TENANT_SCOPED_TABLES.items():
        qualified = f"{SCHEMA}.{table}"
        op.execute(f"ALTER TABLE {qualified} ENABLE ROW LEVEL SECURITY")
        # FORCE is the half that matters: without it the table owner is exempt.
        op.execute(f"ALTER TABLE {qualified} FORCE ROW LEVEL SECURITY")
        op.execute(f"REVOKE ALL ON TABLE {qualified} FROM PUBLIC")
        # A NULL context makes this predicate NULL: reads match nothing, writes are
        # rejected. Absence of tenant context fails closed by construction.
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {qualified}
            FOR ALL
            TO PUBLIC
            USING ({tenant_column} = {SCHEMA}.app_current_tenant_id())
            WITH CHECK ({tenant_column} = {SCHEMA}.app_current_tenant_id())
            """
        )


def downgrade() -> None:
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {SCHEMA}.{table}")
    op.drop_index("ix_workspaces_tenant_id", table_name="workspaces", schema=SCHEMA)
    op.drop_table("workspaces", schema=SCHEMA)
    op.drop_table("tenants", schema=SCHEMA)
    op.execute(f"DROP FUNCTION IF EXISTS {SCHEMA}.app_current_tenant_id()")
    # The schema itself is left in place: the Alembic version table lives in it, so
    # dropping it here would delete the migration history this downgrade just wrote.
